service: cvs-svc-defect
# from 3.0 warnings will be thrown as errors
configValidationMode: warn
plugins:
  - serverless-dynamodb-local
  - serverless-plugin-typescript
  - serverless-plugin-tracing
  - serverless-offline

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs18.x
  tracing:
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "xray:PutTraceSegments"
            - "xray:PutTelemetryRecords"
          Resource:
            - "*"

functions:
  getDefects:
    handler: src/handler.handler
    events:
      - http:
          path: defects
          method: get
  getIvaDefectsByManual:
    handler: src/handler.handler
    events:
      - http:
          path: /defects/iva/manual/{id}
          method: get
  getIvaDefects:
    handler: src/handler.handler
    events:
      - http:
          path: /defects/iva
          method: get

custom:
  serverless-offline:
    port: 3001
  dynamodb:
    stages:
      - dev
      - test
    start:
      port: 8003
      inMemory: true
      migrate: true
      seed: true
      noStart: false
      host: 127.0.0.1
    seed:
      defects:
        sources:
          - table: cvs-local-defects
            sources: [./tests/resources/defects.json]

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-local-defects
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
